name: wai-feature-flags
version: 0.1.0.7
synopsis: Feature flag support for WAI applications.
description: Please see the README at <https://github.com/jwoudenberg/wai-feature-flags>.
author: Jasper Woudenberg
maintainer: mail@jasperwoudenberg.com
copyright: 2023 Jasper Woudenberg
homepage: https://github.com/jwoudenberg/wai-feature-flags#readme
license-file: LICENSE
category: Web
github: jwoudenberg/wai-feature-flags
extra-doc-files:
- README.md
- CHANGELOG.md
data-files:
- frontend/index.html
library:
  dependencies:
  - aeson >= 1.2.4.0 && < 2.3
  - base >= 4.10.1.0 && < 5
  - bytestring >= 0.10.8.2 && < 0.13
  - splitmix >= 0.0.3 && < 0.2
  - text >= 1.2.3.0 && < 2.2
  - unordered-containers >= 0.2.9.0 && < 0.3
  - wai >= 3.2.2.1 && < 3.3
  exposed-modules:
  - Network.FeatureFlags
  source-dirs: src
executables:
  example-app:
    dependencies:
    - base
    - wai
    - wai-feature-flags
    - warp >= 3.3.5 && < 3.4
    main: Main.hs
    source-dirs: example-app
